sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Ll6FxZcVwt1Qv3xi5d/3QEnsA6xcFHWqBYn1lbpgImkc7bYqXHPbX0vJIlJq0eAt4jwt8406W+wa14/FflYzPtPfleOnECFiTrJX0RUy86h8FgtnLCUzKZeaPHyXQaiF2q10OT36OmwHVbtbLFaZvsPamOBEE1h6VEKO9ooyJCKaUNfNovT+bI+Ee5/+bf+bgpaVSPvkZKEfvEOS70x1VBY3P9RG8nPE9NAB5Qf7HbG6RT6Dcy5s+7CgcXyXrYwfD8859DQ8Spbp2k/OIEjuiGevRYdAqM9uDg+Gl6N2sn9AINGpVdIPXy+I8RYJU5SovMmFkM/TynqoKLqTU0TyJhic2edKN6pjfgxnM3XXQugebCzXj3kItXUYrZP02MhHDOs67bMgLKxPSFUpOoJsdhUy9qH3HbhOlysV1cJ7wRifdeQU5mWhTCLvwqVbOhcU5CjRVjNY+04VARXl3CIrutsvPLtD56M0W0I0i/UmfG1Eev9Ro2qub497KKzKyW9JplfB3wJZ8alDdNBV77WRc9x2+WrFWKYfqkC60s8wp6rNehI0EXMA0Fo/354x4fnupDWU0h6fFpCdThviGELi2nNGuX4/NXadKsYUDj1xm3/0wg3fG8NZmvVA0johHRY62nmWf/6C0+c5OeH0G+9f01TLbWcOzeTYHtwtGcTNQ9Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Virginibus-Puerisque-and-Other-Papers_386
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy